apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vigo-azure-ad-service
  labels:
spec:
  itemPath: "vaults/aks-api-vault/items/vigo-azure-ad-service"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: google-gmail-serviceaccount
  labels:
spec:
  itemPath: "vaults/aks-api-vault/items/google-gmail-serviceaccount"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: vigo-azure-ad-service
  name: vigo-azure-ad-service
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: vigo-azure-ad-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: vigo-azure-ad-service
  name: vigo-azure-ad-service
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: vigo-azure-ad-service
  template:
    metadata:
      labels:
        io.kompose.service: vigo-azure-ad-service
    spec:
      volumes:
        - name: credentials
          secret:
            secretName: google-gmail-serviceaccount
      containers:
        - name: vigo-azure-ad-service
          imagePullPolicy: Always
          image: fintlabsacr.azurecr.io/vigo-azure-ad-service:dummy
          volumeMounts:
            - mountPath: /credentials
              name: credentials
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              cpu: "100m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: vigo-azure-ad-service
          env:
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -XX:+UseG1GC -Xmx2G -verbose:gc'}
            - name: fint.invite.mail.serviceaccount
              value: '/credentials/serviceaccount.json'
            - name: fint.azure.qlik.allowed-domains
              value: rogfk.no,trondelagfylke.no,agderfk.no,viken.no,oslo.kommune.no,mrfylke.no,nfk.no,tffk.no,vlfk.no,vtfk.no,innlandetfylke.no,.vgs.no,osloskolen.no,ist.com
            - name: fint.azure.qlik.users.owner
              value: vigo_azure_manager@vigoiks.no
            - name: fint.azure.qlik.send-invitation
              value: "true"
            - name: fint.azure.qlik.synchronize-users
              value: "true"
            - name: fint.azure.qlik.dry-run
              value: "false"
            - name: fint.azure.qlik.user-delete
              value: "false"
