name: Deploy
on:
  push:
    branches:
      - master

env:
  REGISTRY_NAME: fintlabsacr
  API_CLUSTER_NAME: aks-api-fint-2022-02-08
  API_CLUSTER_RESOURCE_GROUP: rg-aks-api
  NAMESPACE: default
  APP_NAME: vigo-azure-ad-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Container build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Set the target Api cluster.
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AKS_API_FINT_GITHUB }}'
          cluster-name: ${{ env.API_CLUSTER_NAME }}
          resource-group: ${{ env.API_CLUSTER_RESOURCE_GROUP }}

      - name: Deploy to Api
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
          images: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}